"""Add inspections table

Revision ID: c9c966c47564
Revises: e87b584bcfae
Create Date: 2025-07-22 18:01:11.704878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c966c47564'
down_revision = 'e87b584bcfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('damage_report', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('inspected_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'COMPLETED', name='inspectionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspections')
    # ### end Alembic commands ###
